### ISSUE TITLE
created folder permissions issues during upgrade/uninstall

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_connect#78]
```ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/json_schema/'
Consider using the `--user` option or check the permissions.```

**Comment by Robbie1977** [comment]
```robbiecourt@Robbies-MacBook-Pro ~ % pip remove VFB_connect
ERROR: unknown command "remove"
robbiecourt@Robbies-MacBook-Pro ~ % pip uninstall VFB_connect
Found existing installation: vfb-connect 1.2.7
Uninstalling vfb-connect-1.2.7:
  Would remove:
    /usr/local/json_schema/VFB_TermInfo_queries.json
    /usr/local/lib/python3.9/site-packages/vfb_connect-1.2.7.dist-info/*
    /usr/local/lib/python3.9/site-packages/vfb_connect/*
Proceed (Y/n)? Y
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 814, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/json_schema/' -> '/private/var/folders/7j/bv0xtj3s4m9dt5zjj_d4j6080000gn/T/pip-uninstall-l_x261qv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/uninstall.py", line 97, in run
    uninstall_pathset = req.uninstall(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 671, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/req/req_uninstall.py", line 384, in remove
    moved.stash(path)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/req/req_uninstall.py", line 282, in stash
    renames(path, new_path)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 307, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 832, in move
    rmtree(src)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 730, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 728, in rmtree
    os.rmdir(path)
PermissionError: [Errno 13] Permission denied: '/usr/local/json_schema/'```
